config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :products
  resources :categories
  resources :line_items

  get 'categorical' => 'storefront#items_by_category'  #routes to the category seed data that shows in the navbar
  

  root 'storefront#all_items'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :category
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category

	has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

   before_filter :authenticate_user! 
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quantity, :brand, :description, :category_id, :image)
  end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController #used as a backroom for admin users to create and update products and categories
  def all_items
  end

  def items_by_brand
  end

  def items_by_category
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">The Seed Market</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Find by Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<% Category.all.each do |cat| %>
          		<li><%= link_to cat.name, categorical_path(id: cat.id) %></li>
          	<% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
         <% if current_user %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %> 
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeedMarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
_form.html.erb

app/views/products/index.html.erb
<h1>Welcome to the Seed store</h1>

app/views/products/new.html.erb
show.html.erb 

app/views/storefront/all_items.html.erb
<h1>Storefront#all_items</h1>
<p>Find me in app/views/storefront/all_items.html.erb</p>

app/views/storefront/items_by_brand.html.erb
<h1>Storefront#items_by_brand</h1>
<p>Find me in app/views/storefront/items_by_brand.html.erb</p>

app/views/storefront/items_by_category.html.erb
<h1>Storefront#items_by_category</h1>
<p>Find me in app/views/storefront/items_by_category.html.erb</p>